# SPDX-License-Identifier: GPL-2.0+
#
# T21 SPL: console + PLL + Innophy DDR2 + SFC NOR loader.
# XBurst1-generic pieces are shared from arch/mips/mach-xburst/.

obj-y	+= soc.o pll.o serial.o sdram.o sfc.o
