// SPDX-License-Identifier: GPL-2.0+
/*
 * Ingenic A1 DDR3 Innophy init (SPL) - per-variant.
 *
 * Faithful transliteration of the vendor ddr_innophy.c sdram_init()
 * path. Register values are transcribed verbatim from the vendor:
 * the per-SKU struct a1_ddr_params (ddr_reg_values_a1{n,nt,l,x}.c)
 * and the per-SKU ddr3_param_t PHY tuning (ddr_innophy.c).
 *
 * Five A1 SKUs, selected by the CONFIG_A1_VARIANT_* Kconfig choice:
 *   A1N  - DDR3-800, 16-bit, 256 MB
 *   A1NT - DDR3-700, 32-bit, 256 MB
 *   A1X  - DDR3-700, 32-bit, 512 MB
 *   A1L  - DDR3-800, 16-bit, 128 MB
 *   A1A  - DDR3-800, 32-bit, 2 GB
 *
 * Only A1N is validated on real silicon; the other four are
 * build-only, faithful transcriptions to be brought up on hardware.
 * A1A has no ready-made vendor table - its values were generated by
 * the vendor ddr_params_creator for the CONFIG_A1A build.
 */

#include <asm/io.h>
#include <linux/delay.h>
#include <mach/a1.h>

/* DDRC register offsets from DDRC_BASE (0xb34f0000) */
#define DDRC_STATUS	0x00
#define DDRC_CFG	0x08
#define DDRC_CTRL	0x10
#define DDRC_LMR	0x18
#define DDRC_AUTOSR_EN	0x28
#define DDRC_AUTOSR_CNT	0x30
#define DDRC_REFCNT	0x38
#define DDRC_TIM(n)	(0x40 + 8 * ((n) - 1))
#define DDRC_MMAP0	0x78
#define DDRC_MMAP1	0x80
#define DDRC_HREGPRO	0xd8

/* DDRC APB registers at DDRC_APB_BASE (0xb3012000) */
#define DDRC_APB_BASE	0xb3012000
#define DDRC_DWCFG	0x00
#define DDRC_DWSTATUS	0x04
#define DDRC_REMAP(n)	(0x08 + 4 * ((n) - 1))
#define DDRC_CGUC0	0x64
#define DDRC_CGUC1	0x68
#define DDRC_PREGPRO	0x6c

/* Innophy PHY register offsets from DDR_PHY_BASE (0xb3011000) */
#define PHY_RST		0x000
#define PHY_MEM_CFG	0x004
#define PHY_TRAIN_CTRL	0x008
#define PHY_CL		0x014
#define PHY_AL		0x018
#define PHY_CWL		0x01c
#define PHY_DQ_WIDTH	0x034
#define PHY_PLL_PD	0x14c
#define PHY_PLL_LOCK	0x180
#define PHY_CALIB_DONE	0x184
/* B-channel read-delay registers - 32-bit DDR soft calibration only */
#define PHY_CALIB_BL1	0x280
#define PHY_CALIB_BL2	0x284
#define PHY_CALIB_BH1	0x2c0
#define PHY_CALIB_BH2	0x2c4

/*
 * The DDRC_LMR (load mode register) command word, as built by the
 * vendor DDRC_LMR_MR() macro: DLMR(2) | START(1) | CMD_LMR(2<<6) plus
 * the 16-bit MR data at bit 12 and the 3-bit bank at bit 9.
 */
#define LMR_BASE	0x83		/* DLMR | START | CMD_LMR */
#define LMR_ZQCL	0xc3		/* DLMR | START | CMD_ZQCL_CS0 */

struct a1_ddr_variant {
	/* DDRC controller registers */
	u32 cfg;
	u32 tim[5];
	u32 mmap0, mmap1;
	u32 refcnt;
	u32 autosr_cnt;
	u32 remap[5];
	u32 mr[4];		/* raw DDR3 mode register values MR0..MR3 */
	/* Innophy PHY tuning (vendor ddr3_param_t) */
	u8 cl, cwl;
	u8 odt_pd, odt_pu;
	u8 drvcmd_pd, drvcmd_pu;
	u8 drvcmdck_pd, drvcmdck_pu;
	u8 dq_drv_a_pd, dq_drv_a_pu;
	u8 dq_drv_b_pd, dq_drv_b_pu;
	u8 dq_a, dq_b;
	u8 vref;
	u8 kgd_odt, kgd_ds;
	u8 dqs_a, dqs_b;
	bool dw32;		/* true: 32-bit data bus; false: 16-bit */
};

#if defined(CONFIG_A1_VARIANT_A1N)
static const struct a1_ddr_variant a1_ddr = {
	.cfg = 0x4a004a35,
	.tim = { 0x07130d08, 0x0809070b, 0x030c040c, 0x252b1f07, 0x80069055 },
	.mmap0 = 0x000020f0, .mmap1 = 0x00003000,
	.refcnt = 0x41c30081, .autosr_cnt = 0x40000c41,
	.remap = { 0x030f0e0d, 0x07060504, 0x0b0a0908, 0x0201000c, 0x13121110 },
	.mr = { 0x00001f70, 0x00010002, 0x00020018, 0x00030000 },
	.cl = 0x0b, .cwl = 0x08,
	.odt_pd = 1, .odt_pu = 0,
	.drvcmd_pd = 0x0e, .drvcmd_pu = 0x0e,
	.drvcmdck_pd = 0x0e, .drvcmdck_pu = 0x0e,
	.dq_drv_a_pd = 0x14, .dq_drv_a_pu = 0x14,
	.dq_drv_b_pd = 0x14, .dq_drv_b_pu = 0x14,
	.dq_a = 0x10, .dq_b = 0x07, .vref = 0x80,
	.kgd_odt = 1, .kgd_ds = 1,
	.dqs_a = 0x20, .dqs_b = 0x20,
	.dw32 = false,
};
#elif defined(CONFIG_A1_VARIANT_A1NT)
static const struct a1_ddr_variant a1_ddr = {
	.cfg = 0x2a002a35,
	.tim = { 0x07120c08, 0x0809060b, 0x030a040a, 0x20261b06, 0x80058054 },
	.mmap0 = 0x000020f0, .mmap1 = 0x00003000,
	.refcnt = 0x67a90081, .autosr_cnt = 0x26000aab,
	.remap = { 0x030f0e0d, 0x07060504, 0x0b0a0908, 0x0201000c, 0x13121110 },
	.mr = { 0x00001d70, 0x00010002, 0x00020018, 0x00030000 },
	.cl = 0x0b, .cwl = 0x08,
	.odt_pd = 3, .odt_pu = 1,
	.drvcmd_pd = 0x0e, .drvcmd_pu = 0x0e,
	.drvcmdck_pd = 0x0e, .drvcmdck_pu = 0x0e,
	.dq_drv_a_pd = 0x14, .dq_drv_a_pu = 0x14,
	.dq_drv_b_pd = 0x14, .dq_drv_b_pu = 0x14,
	.dq_a = 0x10, .dq_b = 0x0f, .vref = 0x80,
	.kgd_odt = 2, .kgd_ds = 1,
	.dqs_a = 0x20, .dqs_b = 0x21,
	.dw32 = true,
};
#elif defined(CONFIG_A1_VARIANT_A1X)
static const struct a1_ddr_variant a1_ddr = {
	.cfg = 0x4a004a35,
	.tim = { 0x07120c08, 0x0809060b, 0x030a040a, 0x20261b06, 0x80058054 },
	.mmap0 = 0x000020e0, .mmap1 = 0x00004000,
	.refcnt = 0x79a90081, .autosr_cnt = 0x38000aab,
	.remap = { 0x03100f0e, 0x07060504, 0x0b0a0908, 0x01000d0c, 0x13121102 },
	.mr = { 0x00001d70, 0x00010002, 0x00020018, 0x00030000 },
	.cl = 0x0b, .cwl = 0x08,
	.odt_pd = 5, .odt_pu = 11,
	.drvcmd_pd = 0x1e, .drvcmd_pu = 0x1e,
	.drvcmdck_pd = 0x1e, .drvcmdck_pu = 0x1e,
	.dq_drv_a_pd = 0x0f, .dq_drv_a_pu = 0x0f,
	.dq_drv_b_pd = 0x0f, .dq_drv_b_pu = 0x0f,
	.dq_a = 0x0f, .dq_b = 0x0d, .vref = 0xa0,
	.kgd_odt = 2, .kgd_ds = 0,
	.dqs_a = 0x21, .dqs_b = 0x21,
	.dw32 = true,
};
#elif defined(CONFIG_A1_VARIANT_A1L)
static const struct a1_ddr_variant a1_ddr = {
	.cfg = 0x2a002a35,
	.tim = { 0x07130d08, 0x0708070a, 0x030c040c, 0x21281d07, 0x80059045 },
	.mmap0 = 0x000020f8, .mmap1 = 0x00002800,
	.refcnt = 0x41c30081, .autosr_cnt = 0x40000c41,
	.remap = { 0x030e0d0c, 0x07060504, 0x0b0a0908, 0x0f020100, 0x13121110 },
	.mr = { 0x00001f60, 0x00010002, 0x00020018, 0x00030000 },
	.cl = 0x0a, .cwl = 0x07,
	.odt_pd = 1, .odt_pu = 1,
	.drvcmd_pd = 0x0e, .drvcmd_pu = 0x0e,
	.drvcmdck_pd = 0x0e, .drvcmdck_pu = 0x0e,
	.dq_drv_a_pd = 0x14, .dq_drv_a_pu = 0x14,
	.dq_drv_b_pd = 0x14, .dq_drv_b_pu = 0x14,
	.dq_a = 0x0e, .dq_b = 0x0e, .vref = 0x80,
	.kgd_odt = 1, .kgd_ds = 1,
	.dqs_a = 0x1c, .dqs_b = 0x1c,
	.dw32 = false,
};
#elif defined(CONFIG_A1_VARIANT_A1A)
static const struct a1_ddr_variant a1_ddr = {
	.cfg = 0x8a008a35,
	.tim = { 0x08140d09, 0x0707070a, 0x030c040c, 0x252a1f07, 0x80059045 },
	.mmap0 = 0x00000000, .mmap1 = 0x0000ff00,
	.refcnt = 0xcdc30083, .autosr_cnt = 0x8c001883,
	.remap = { 0x03121110, 0x07060504, 0x0b0a0908, 0x0f0e0d0c, 0x13020100 },
	.mr = { 0x00001f60, 0x00010002, 0x00020020, 0x00030000 },
	.cl = 0x0a, .cwl = 0x07,
	.odt_pd = 7, .odt_pu = 12,
	.drvcmd_pd = 0x0e, .drvcmd_pu = 0x0e,
	.drvcmdck_pd = 0x0e, .drvcmdck_pu = 0x0e,
	.dq_drv_a_pd = 0x14, .dq_drv_a_pu = 0x14,
	.dq_drv_b_pd = 0x14, .dq_drv_b_pu = 0x14,
	.dq_a = 0x14, .dq_b = 0x14, .vref = 0x96,
	.kgd_odt = 1, .kgd_ds = 1,
	.dqs_a = 0x23, .dqs_b = 0x23,
	.dw32 = true,
};
#else
#error "A1: no DDR variant selected (CONFIG_A1_VARIANT_*)"
#endif

static void ddr_writel(u32 val, u32 off)
{
	writel(val, (void __iomem *)(DDRC_BASE + off));
}

static u32 ddr_readl(u32 off)
{
	return readl((void __iomem *)(DDRC_BASE + off));
}

static void apb_writel(u32 val, u32 off)
{
	writel(val, (void __iomem *)(DDRC_APB_BASE + off));
}

static u32 apb_readl(u32 off)
{
	return readl((void __iomem *)(DDRC_APB_BASE + off));
}

static void phy_writel(u32 val, u32 off)
{
	writel(val, (void __iomem *)(DDR_PHY_BASE + off));
}

static u32 phy_readl(u32 off)
{
	return readl((void __iomem *)(DDR_PHY_BASE + off));
}

static void phy_writel_idx(u32 val, u32 idx)
{
	writel(val, (void __iomem *)(DDR_PHY_BASE + idx * 4));
}

static u32 a1_c0_count(void)
{
	u32 c;

	__asm__ __volatile__("mfc0 %0, $9; nop" : "=r"(c));
	return c;
}

/*
 * Microsecond delay built on the CP0 Count register. The SPL has no
 * timer peripheral and udelay() is not available; earlier revisions
 * used raw busy loops whose duration was unpredictable (compiler,
 * cache, CPU clock), leaving the DDR PHY reset/training delays too
 * short and the DRAM marginally trained.
 *
 * Count advances at most at the CPU clock (APLL); assuming the full
 * rate makes the delay never shorter than requested - at worst ~2x
 * long if Count actually runs at CPU/2, which is harmless. The
 * iteration cap keeps the loop bounded if Count is ever frozen.
 */
static void a1_udelay(u32 us)
{
	u32 start = a1_c0_count();
	u32 ticks = us * (CONFIG_A1_APLL_MHZ);
	u32 cap = ticks * 8u + 100000u;

	while ((a1_c0_count() - start) < ticks && --cap)
		;
}

/* Build the DDRC_LMR command word for a raw DDR3 mode register value. */
static u32 lmr_mr(u32 mr)
{
	return LMR_BASE | ((mr & 0xffff) << 12) | (((mr >> 16) & 0x7) << 9);
}

static void ddr_clk_set(void)
{
	void __iomem *cpm = (void __iomem *)CPM_BASE;
	u32 val;

	/* Ungate DDR clock (CLKGR0 bit 3) */
	val = readl(cpm + CPM_CLKGR0);
	val &= ~CPM_CLKGR0_DDR;
	writel(val, cpm + CPM_CLKGR0);

	/*
	 * Re-derive the DDR clock from MPLL (vendor clk_set_rate(DDR)).
	 * pll_init reprogrammed MPLL, so the DDRCDR divider must be
	 * re-latched: clear the divider [3:0] and the CE/BUSY/STOP
	 * field [29:24], set divider 1 (DDR = MPLL/2) and pulse CE,
	 * then wait for BUSY to clear. Skipping this leaves the DDR
	 * clock running off a divider that never re-sampled the new
	 * MPLL - a jittery clock that mistunes RX calibration.
	 */
	val = readl(cpm + CPM_DDRCDR);
	val &= ~(0xf | (0x3f << 24));
	val |= (1 << 29) | 0x1;
	writel(val, cpm + CPM_DDRCDR);
	{
		int t = 100000;

		while ((readl(cpm + CPM_DDRCDR) & (1 << 28)) && --t)
			;
	}
}

static void ddrc_reset_phy(void)
{
	ddr_writel(0x00f00000, DDRC_CTRL);
	a1_udelay(1000);			/* vendor: mdelay(1) */
	ddr_writel(0x00800000, DDRC_CTRL);	/* dfi_reset_n low */
	a1_udelay(1000);			/* vendor: mdelay(1) */
}

static void phy_rmw(u32 off, u32 mask, u32 val)
{
	u32 v = phy_readl(off);

	v &= ~mask;
	v |= val;
	phy_writel(v, off);
}

static void ddrp_pll_init(void)
{
	/*
	 * Read-modify-write each PHY register (vendor ddrp_pll_init does
	 * `val &= ~mask; val |= field`). The bootrom leaves meaningful
	 * state in the upper bits of these PHY registers; a full write
	 * clobbers it and perturbs the PHY enough that the RX hard
	 * calibration converges to a marginal point.
	 *
	 * DQ width: 0x3 = 16-bit, 0xf = 32-bit (vendor reg1f [3:0]).
	 */
	phy_rmw(PHY_MEM_CFG, 0xff, 0x0a);
	phy_rmw(PHY_DQ_WIDTH, 0x0f, a1_ddr.dw32 ? 0x0f : 0x03);
	phy_rmw(PHY_RST, 0xff, 0x0d);
	phy_rmw(PHY_CWL, 0x0f, a1_ddr.cwl);
	phy_rmw(PHY_CL, 0x0f, a1_ddr.cl);
	phy_writel(0x00, PHY_AL);	/* vendor writes AL = 0 outright */
	phy_rmw(PHY_PLL_PD, 0xff, 0x00);

	/*
	 * Innophy PHY PLL band select is rate-dependent (vendor
	 * ddrp_pll_init): the 650-900 MHz band leaves PLL_CTRL and
	 * PLL_PD at their reset/zero value. All A1 SKUs run DDR in
	 * 700-804 MHz, so that band always applies.
	 */

	while (!(phy_readl(PHY_PLL_LOCK) & 0x4))
		;
}

static void ddr_param_write(void)
{
	/* ODT pull-down/up for all 4 byte lanes */
	static const u32 odt_pd_idx[] = { 0x140, 0x150, 0x160, 0x170 };
	static const u32 odt_pu_idx[] = { 0x141, 0x151, 0x161, 0x171 };
	int i;

	for (i = 0; i < 4; i++) {
		phy_writel_idx(a1_ddr.odt_pd, odt_pd_idx[i]);
		phy_writel_idx(a1_ddr.odt_pu, odt_pu_idx[i]);
	}

	/* CMD drive strength */
	phy_writel_idx(a1_ddr.drvcmd_pd, 0x130);
	phy_writel_idx(a1_ddr.drvcmd_pu, 0x131);
	/* CK drive strength */
	phy_writel_idx(a1_ddr.drvcmdck_pd, 0x132);
	phy_writel_idx(a1_ddr.drvcmdck_pu, 0x133);

	/* DQ drive A lanes (pull-down/up) */
	static const u32 drv_a_pd[] = { 0x142, 0x152 };
	static const u32 drv_a_pu[] = { 0x143, 0x153 };
	for (i = 0; i < 2; i++) {
		phy_writel_idx(a1_ddr.dq_drv_a_pd, drv_a_pd[i]);
		phy_writel_idx(a1_ddr.dq_drv_a_pu, drv_a_pu[i]);
	}
	/* DQ drive B lanes */
	static const u32 drv_b_pd[] = { 0x162, 0x172 };
	static const u32 drv_b_pu[] = { 0x163, 0x173 };
	for (i = 0; i < 2; i++) {
		phy_writel_idx(a1_ddr.dq_drv_b_pd, drv_b_pd[i]);
		phy_writel_idx(a1_ddr.dq_drv_b_pu, drv_b_pu[i]);
	}

	/* DQS A delay */
	static const u32 dqs_a[] = { 0x1d2, 0x1e7, 0x1ea, 0x1eb };
	for (i = 0; i < 4; i++)
		phy_writel_idx(a1_ddr.dqs_a, dqs_a[i]);
	/* DQS B delay */
	static const u32 dqs_b[] = { 0x232, 0x247, 0x24a, 0x24b };
	for (i = 0; i < 4; i++)
		phy_writel_idx(a1_ddr.dqs_b, dqs_b[i]);

	/* Per-DQ-bit delay offsets from vendor DQxRxOFFSET table */
	static const u32 dq_off[16] = {
		0x02, 0x04, 0x06, 0x08, 0x0a, 0x0c, 0x0e, 0x10,
		0x17, 0x19, 0x1b, 0x1d, 0x1f, 0x21, 0x23, 0x25,
	};
	/* Channel A (base 0x1c0) */
	for (i = 0; i < 16; i++)
		phy_writel_idx(a1_ddr.dq_a, 0x1c0 + dq_off[i]);
	/* Channel B (base 0x220) */
	for (i = 0; i < 16; i++)
		phy_writel_idx(a1_ddr.dq_b, 0x220 + dq_off[i]);

	/* VREF for all 4 byte lanes */
	static const u32 vref_idx[] = { 0x147, 0x157, 0x167, 0x177 };
	for (i = 0; i < 4; i++)
		phy_writel_idx(a1_ddr.vref, vref_idx[i]);
}

static void ddrc_dfi_init(void)
{
	int timeout;
	u32 mr1;

	/* DFI init handshake: dfi_init_start + bus width (32-bit: |1) */
	apb_writel(a1_ddr.dw32 ? 0x09 : 0x08, DDRC_DWCFG);
	apb_writel(a1_ddr.dw32 ? 0x01 : 0x00, DDRC_DWCFG);

	timeout = 1000000;
	while (!(apb_readl(DDRC_DWSTATUS) & 0x1) && --timeout)
		;
	a1_udelay(50);				/* vendor: udelay(50) */

	ddr_writel(0x00000000, DDRC_CTRL);	/* dfi_reset_n high */
	ddr_writel(a1_ddr.cfg, DDRC_CFG);
	a1_udelay(500);				/* vendor: udelay(500) */
	ddr_writel(0x00000002, DDRC_CTRL);	/* CKE high */
	a1_udelay(10);				/* vendor: udelay(10) */

	/* MR2 */
	ddr_writel(0x00000000, DDRC_LMR);
	a1_udelay(5);
	ddr_writel(lmr_mr(a1_ddr.mr[2]), DDRC_LMR);
	a1_udelay(5);
	/* MR3 */
	ddr_writel(0x00000000, DDRC_LMR);
	a1_udelay(5);
	ddr_writel(lmr_mr(a1_ddr.mr[3]), DDRC_LMR);
	a1_udelay(5);
	/* MR1 - patched with kgd_odt (A9/A6/A2) and kgd_ds (A5/A1) */
	mr1 = (a1_ddr.mr[1] & 0xfffffd99)
	    | (((a1_ddr.kgd_odt >> 2) & 1) << 9)
	    | (((a1_ddr.kgd_odt >> 1) & 1) << 6)
	    | ((a1_ddr.kgd_odt & 1) << 2)
	    | (((a1_ddr.kgd_ds >> 1) & 1) << 5)
	    | ((a1_ddr.kgd_ds & 1) << 1);
	ddr_writel(0x00000000, DDRC_LMR);
	a1_udelay(5);
	ddr_writel(lmr_mr(mr1), DDRC_LMR);
	a1_udelay(5);
	/* MR0 */
	ddr_writel(0x00000000, DDRC_LMR);
	a1_udelay(5);
	ddr_writel(lmr_mr(a1_ddr.mr[0]), DDRC_LMR);
	a1_udelay(5);
	/* ZQCL CS0 */
	ddr_writel(LMR_ZQCL, DDRC_LMR);
	a1_udelay(5);
}

static void ddrc_prev_init(void)
{
	ddr_writel(a1_ddr.tim[0], DDRC_TIM(1));
	ddr_writel(a1_ddr.tim[1], DDRC_TIM(2));
	ddr_writel(a1_ddr.tim[2], DDRC_TIM(3));
	ddr_writel(a1_ddr.tim[3], DDRC_TIM(4));
	ddr_writel(a1_ddr.tim[4], DDRC_TIM(5));
	ddr_writel(a1_ddr.mmap0, DDRC_MMAP0);
	ddr_writel(a1_ddr.mmap1, DDRC_MMAP1);
	ddr_writel(0x00008092, DDRC_CTRL);
}

/*
 * 32-bit DDR only: the hardware calibration tunes the A-channel read
 * delay but not the B-channel (upper 16 bits) - the BL/BH delay
 * registers are "soft calibration only". Sweep the B-channel delay
 * across its range, test a DRAM scratch buffer through the uncached
 * window, and centre the delay on the passing window. Mirrors the
 * vendor dw32 soft-calibration loop in ddr_innophy.c.
 */
static void ddrp_bchan_soft_calib(void)
{
	volatile u32 *buf = (volatile u32 *)0xa0100000;	/* uncached DRAM */
	const u32 pat = 0xf0f0f0f0;
	int c, first = -1, last = -1, sel;
	int i, ok;

	for (c = 0; c < 0x3ff; c++) {
		phy_writel((c >> 7) & 0x7, PHY_CALIB_BL1);
		phy_writel(((c & 0x1f) << 3) | ((c >> 5) & 0x3), PHY_CALIB_BL2);
		phy_writel((c >> 7) & 0x7, PHY_CALIB_BH1);
		phy_writel(((c & 0x1f) << 3) | ((c >> 5) & 0x3), PHY_CALIB_BH2);

		for (i = 0; i < 4096; i++)
			buf[i] = pat;
		ok = 1;
		for (i = 0; i < 4096; i++) {
			if ((buf[i] & 0xffff0000) != (pat & 0xffff0000)) {
				ok = 0;
				break;
			}
		}
		if (ok) {
			if (first < 0)
				first = c;
			last = c;
		}
	}

	if (first < 0) {
		/* no passing window - vendor fallback */
		phy_writel(0x1c, PHY_CALIB_BL1);
		phy_writel(0x1c, PHY_CALIB_BH1);
		return;
	}

	/* centre on the passing window (the vendor picks calv[m/2]) */
	sel = (first + last) / 2;
	phy_writel((sel >> 7) & 0x7, PHY_CALIB_BL1);
	phy_writel(((sel & 0x1f) << 3) | ((sel >> 5) & 0x3), PHY_CALIB_BL2);
	phy_writel((sel >> 7) & 0x7, PHY_CALIB_BH1);
	phy_writel(((sel & 0x1f) << 3) | ((sel >> 5) & 0x3), PHY_CALIB_BH2);
}

static void ddrp_hardware_calibration(void)
{
	u32 done = a1_ddr.dw32 ? 0xf : 0x3;	/* 4 vs 2 byte lanes */

	phy_writel(0x00, PHY_TRAIN_CTRL);
	phy_readl(PHY_TRAIN_CTRL);
	phy_writel(0x01, PHY_TRAIN_CTRL);

	while ((phy_readl(PHY_CALIB_DONE) & 0xf) != done)
		;

	u32 ctrl = phy_readl(PHY_TRAIN_CTRL);

	phy_writel(ctrl & ~0x01, PHY_TRAIN_CTRL);
}

static void ddrc_post_init(void)
{
	int i;

	ddr_writel(a1_ddr.refcnt, DDRC_REFCNT);

	for (i = 0; i < 5; i++)
		apb_writel(a1_ddr.remap[i], DDRC_REMAP(i + 1));

	ddr_writel(0x0000b092, DDRC_CTRL);
	apb_writel(0x11111111, DDRC_CGUC0);
	apb_writel(0x00000113, DDRC_CGUC1);
}

static void ddrp_set_rfifo(void)
{
	u32 val;

	val = phy_readl(PHY_MEM_CFG);
	phy_writel(val | (1u << 5), PHY_MEM_CFG);

	val = phy_readl(DDR_PHY_OFFSET + 0x038);
	val &= ~0x7;
	val |= 0x3;
	phy_writel(val, DDR_PHY_OFFSET + 0x038);
}

void sdram_init(void)
{
	ddr_clk_set();
	ddrc_reset_phy();
	ddrp_pll_init();
	ddr_param_write();
	ddrc_dfi_init();
	ddrc_prev_init();
	ddrp_hardware_calibration();
	ddrc_post_init();

	if (a1_ddr.dw32)
		ddrp_bchan_soft_calib();

	ddr_writel(a1_ddr.autosr_cnt, DDRC_AUTOSR_CNT);
	ddr_writel(0x00000000, DDRC_AUTOSR_EN);
	ddr_writel(0x00000001, DDRC_HREGPRO);
	apb_writel(0x00000001, DDRC_PREGPRO);

	ddrp_set_rfifo();
}
