/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Ingenic T41NQ DDR3 controller + Innophy PHY register values.
 *
 * Generated by vendor `tools/ingenic-tools/ddr_params_creator` with
 * `isvp_t41nq_sfc_nor` defconfig on the T41-1.2.6 branch:
 *   CONFIG_T41NQ + CONFIG_DDR3_W631GU6NG + DDR=700MHz + DW32=0
 *   + CS0-only.
 *
 * 128 MiB single chip W631GU6NG, 16-bit DDR3-1400 @ 700 MHz,
 * APLL=1104, MPLL=1400.
 */

#ifndef __T41NQ_DDR_H__
#define __T41NQ_DDR_H__

#define CONFIG_T41_DDR3		1

/* DDR controller geometry (from ddr_params_creator output) */
#define DDR_ROW			13
#define DDR_COL			10
#define DDR_BANK8		1
#define CONFIG_DDR_DW32		0	/* 16-bit bus */
#define CONFIG_DDR_CS0		1
#define CONFIG_DDR_CS1		0
#define DDR_CHIP_0_SIZE		0x08000000	/* 128 MiB */
#define DDR_CHIP_1_SIZE		0

/* Clock target: MPLL=1400 -> DDR=MPLL/2=700 MHz */
#define DDR_MPLL_RATE		1400000000U
#define DDR_TARGET_RATE		(DDR_MPLL_RATE / 2U)

/* T41NQ PLL MNOD values from vendor isvp_t41.h:
 *   APLL = 1104 MHz: (92<<20)|(1<<14)|(2<<11)|(1<<8)
 *   MPLL = 1400 MHz: (350<<20)|(2<<14)|(3<<11)|(1<<8)
 *   VPLL = 1188 MHz: (99<<20)|(1<<14)|(2<<11)|(1<<8)
 */
#define T41_APLL_MNOD		((92 << 20) | (1 << 14) | (2 << 11) | (1 << 8))
#define T41_MPLL_MNOD		((350 << 20) | (2 << 14) | (3 << 11) | (1 << 8))
#define T41_VPLL_MNOD		((99 << 20) | (1 << 14) | (2 << 11) | (1 << 8))

/* DDRC register values from ddr_params_creator (T41NQ + W631GU6NG + 700 MHz + 16-bit) */
#define DDRC_CFG_VALUE		0x02002a35
#define DDRC_CTRL_VALUE		0x0000b092
#define DDRC_DLMR_VALUE		0x00000000
#define DDRC_MMAP0_VALUE	0x000020f8
#define DDRC_MMAP1_VALUE	0x00002800
#define DDRC_REFCNT_VALUE	0x67aa0083
#define DDRC_TIMING1_VALUE	0x07120b08
#define DDRC_TIMING2_VALUE	0x0708060a
#define DDRC_TIMING3_VALUE	0x030a040a
#define DDRC_TIMING4_VALUE	0x19221805
#define DDRC_TIMING5_VALUE	0x00050054
#define DDRC_AUTOSR_CNT_VALUE	0x26001556
#define DDRC_AUTOSR_EN_VALUE	0x00000000
#define DDRC_HREGPRO_VALUE	0x00000001
#define DDRC_PREGPRO_VALUE	0x00000001
#define DDRC_CGUC0_VALUE	0x11111111
#define DDRC_CGUC1_VALUE	0x00000113

/* PHY (Innophy DDR3) */
#define DDRP_MEMCFG_VALUE	0x0000000a
#define DDRP_CL_VALUE		0x0000000a	/* CL=10 */
#define DDRP_CWL_VALUE		0x00000008	/* CWL=8 */
#define DDR_MR0_VALUE		0x00001d50
#define DDR_MR1_VALUE		0x00010006
#define DDR_MR2_VALUE		0x00020018
#define DDR_MR3_VALUE		0x00030000

/* REMMAP_ARRAY from ddr_params_creator */
#define T41_REMMAP_ARRAY	{ 0x030e0d0c, 0x07060504, 0x0b0a0908, \
				  0x0f020100, 0x13121110 }

#endif /* __T41NQ_DDR_H__ */
