# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_CLK_INGENIC_A1) += clk-a1.o
obj-$(CONFIG_CLK_INGENIC_T10) += clk-t10.o
obj-$(CONFIG_CLK_INGENIC_T20) += clk-t20.o
obj-$(CONFIG_CLK_INGENIC_T21) += clk-t21.o
obj-$(CONFIG_CLK_INGENIC_T23) += clk-t23.o
obj-$(CONFIG_CLK_INGENIC_T30) += clk-t30.o
obj-$(CONFIG_CLK_INGENIC_T31) += clk-t31.o
obj-$(CONFIG_CLK_INGENIC_T32) += clk-t32.o
obj-$(CONFIG_CLK_INGENIC_T33) += clk-t33.o
obj-$(CONFIG_CLK_INGENIC_T40) += clk-t40.o
obj-$(CONFIG_CLK_INGENIC_T41) += clk-t41.o
