# SPDX-License-Identifier: GPL-2.0+
#
# T20 SPL: console + PLL + SFC; DDR is the DT-driven DWC UCLASS_RAM driver
# in drivers/ram/ingenic/ddr_t20.c. XBurst1-generic pieces are shared from
# arch/mips/mach-xburst/.

obj-y	+= soc.o pll.o serial.o sfc.o
