# SPDX-License-Identifier: GPL-2.0+
#
# T20 SPL: console + PLL + Synopsys DWC DDR2. SFC NOR loader
# (sfc.o) lands with a later stage. XBurst1-generic pieces are
# shared from arch/mips/mach-xburst/.

obj-y	+= soc.o pll.o serial.o sdram.o
