# SPDX-License-Identifier: GPL-2.0+
#
# T20 SPL: stage 1 = console + PLL. DWC DDR (sdram.o) + SFC NOR
# loader (sfc.o) land with later stages. XBurst1-generic pieces
# shared from arch/mips/mach-xburst/.

obj-y	+= soc.o pll.o serial.o
