# SPDX-License-Identifier: GPL-2.0+

extra-$(CONFIG_XPL_BUILD)	:= start.o

obj-y				+= cpu.o
obj-$(CONFIG_SOC_T10)		+= t10/
obj-$(CONFIG_SOC_T20)		+= t20/
obj-$(CONFIG_SOC_T21)		+= t21/
obj-$(CONFIG_SOC_T23)		+= t23/
obj-$(CONFIG_SOC_T30)		+= t30/
obj-$(CONFIG_SOC_T31)		+= t31/
